#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-memoise
Version  : 1.1.0
Release  : 46
URL      : https://cran.r-project.org/src/contrib/memoise_1.1.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/memoise_1.1.0.tar.gz
Summary  : Memoisation of Functions
Group    : Development/Tools
License  : MIT
BuildRequires : clr-R-helpers

%description
again with the same arguments it returns the pre-computed value.

%prep
%setup -q -c -n memoise

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1502409306

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1502409306
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library memoise
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library memoise
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library memoise
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/memoise/DESCRIPTION
/usr/lib64/R/library/memoise/INDEX
/usr/lib64/R/library/memoise/LICENSE
/usr/lib64/R/library/memoise/Meta/Rd.rds
/usr/lib64/R/library/memoise/Meta/features.rds
/usr/lib64/R/library/memoise/Meta/hsearch.rds
/usr/lib64/R/library/memoise/Meta/links.rds
/usr/lib64/R/library/memoise/Meta/nsInfo.rds
/usr/lib64/R/library/memoise/Meta/package.rds
/usr/lib64/R/library/memoise/NAMESPACE
/usr/lib64/R/library/memoise/NEWS.md
/usr/lib64/R/library/memoise/R/memoise
/usr/lib64/R/library/memoise/R/memoise.rdb
/usr/lib64/R/library/memoise/R/memoise.rdx
/usr/lib64/R/library/memoise/help/AnIndex
/usr/lib64/R/library/memoise/help/aliases.rds
/usr/lib64/R/library/memoise/help/memoise.rdb
/usr/lib64/R/library/memoise/help/memoise.rdx
/usr/lib64/R/library/memoise/help/paths.rds
/usr/lib64/R/library/memoise/html/00Index.html
/usr/lib64/R/library/memoise/html/R.css
